useTabs: false
singleQuote: true
semi: false
tabWidth: 2
printWidth: 120
trailingComma: 'none'
htmlWhitespaceSensitivity: 'strict'
bracketSameLine: true
jsxSingleQuote: false
jsxBracketSameLine: false
bracketSpacing: true
arrowParens: 'always'
plugins: ['prettier-plugin-tailwindcss']
